name: Test PC Skeletor code

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip setuptools
          pip install mistree==1.2.0
          pip install .
      - name: 'Test PC Skeletor'
        run: |
          pytest .
          ls -la 
          ls -la ${{ github.workspace }}
          pwd
